# Generated by Django 2.2.4 on 2020-06-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wish_list',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='name',
        ),
    ]
