# Generated by Django 2.2.4 on 2020-06-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review_app', '0002_auto_20200619_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wish_list',
            field=models.ManyToManyField(related_name='items_wish', to='belt_review_app.User'),
        ),
    ]
