# Generated by Django 2.2.4 on 2020-06-21 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review_app', '0004_auto_20200619_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='wish_list',
            new_name='favoritors',
        ),
    ]
